import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation,PresentationFile,FileBlob} from '@oai/artifact-tool';
const W='C:/Users/David Bayha/Documents/Codex/2026-09-09/this-is-my-phd-research-im';
const R='C:/Users/David Bayha/Documents/GitHub/BCA';
const skill='C:/Users/David Bayha/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
const build=W+'/work/advisor_answers_20260929/build';
const out=W+'/outputs/advisor_answers_20260929';
await fs.mkdir(out,{recursive:true});
const {resolvePresentationFont,applyPresentationChartFont,makeNativeBulletParagraphs,finalizePresentation}=await import(pathToFileURL(skill+'/container_tools/artifact_tool_utils.mjs'));
const font=resolvePresentationFont();
const data=JSON.parse(await fs.readFile(R+'/outputs/current_results/2026-09-29/plot_data.json','utf8'));
const C={navy:'#20365C',ink:'#192737',teal:'#087F8C',orange:'#B46226',muted:'#5C6877',pale:'#F1F4F8',line:'#D8DFE7',white:'#FFFFFF'};
const pres=Presentation.create({slideSize:{width:1280,height:720}});
const slides=[], tableSlides=[], chartSlides=[];
const source=p=>'Evidence: '+R+'/'+p;
const current=source('outputs/current_results/2026-09-29/plot_data.json')+'\n'+source('outputs/current_results/2026-09-29/ANALYSIS.md');
const protocol=source('docs/superpowers/plans/2026-09-28-ood-robustness-v2.md');
const pilot=source('outputs/advisor_progress/2026-09-29/ADVISOR_BRIEF.md');
const weighted=source('docs/WEIGHTED_CONFORMAL_DESIGN.md');
function text(sl,t,x,y,w,h,size=28,color=C.ink,bold=false){const sh=sl.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});sh.text=t;sh.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none',verticalAlignment:'middle'};return sh;}
function add(title,notes,footer=''){const sl=pres.slides.add();sl.background.fill=C.white;sl.shapes.add({geometry:'rect',position:{left:0,top:0,width:1280,height:110},fill:C.navy,line:{fill:'none',width:0}});text(sl,title,52,19,1176,75,42,C.white,true);text(sl,footer,54,660,1090,37,17,C.muted);text(sl,String(slides.length+1),1180,660,48,37,18,C.muted);sl.speakerNotes.textFrame.setText(notes);slides.push({title,notes,footer,slide:sl,bullets:[],callouts:[]});return sl;}
function call(sl,t,x,y,w,h,size=30,color=C.navy,bold=true){slides.at(-1).callouts.push(t);return text(sl,t,x,y,w,h,size,color,bold);}
function bullets(sl,items,x=66,y=185,w=1145,h=385,size=30){slides.at(-1).bullets.push(...items);const sh=text(sl,'',x,y,w,h,size);sh.text=makeNativeBulletParagraphs(items,{marginLeftPoints:18,hangingPoints:9,spaceAfterPoints:19});sh.text.style={typeface:font,fontSize:size,color:C.ink,autoFit:'none'};return sh;}
function table(sl,values,widths,{x=52,y=173,h=400,size=25}={}){const t=sl.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width:widths.reduce((a,b)=>a+b,0),height:h,columnWidths:widths,values});t.borders.assign({fill:C.line,width:1,style:'solid'});for(let r=0;r<values.length;r++){t.rows[r].height=h/values.length;for(let c=0;c<values[0].length;c++){const ce=t.getCell(r,c);ce.fill=r===0?C.navy:r%2?C.white:C.pale;ce.text.style={typeface:font,fontSize:size,color:r===0?C.white:C.ink,bold:r===0,autoFit:'none'};}}t.cells.block({row:0,column:0,rowCount:values.length,columnCount:values[0].length}).assign({margins:{left:12,right:10,top:8,bottom:7},anchor:'center'});tableSlides.push(slides.length);slides.at(-1).table=values;return t;}
function chart(sl,type,config){if(slides.length===8)config.xAxis.tickLabelPosition='low';const c=sl.charts.add(type,{chartFill:C.white,plotAreaFill:C.white,chartLine:{fill:'none',width:0},...config});applyPresentationChartFont(c,{fontFamily:font});chartSlides.push(slides.length);return c;}
const fmt=x=>(x>=0?'+':'−')+Math.abs(x).toFixed(2);
const find=(h,e,seed=202609171)=>{const p=data.paired_summaries.find(p=>p.host===h&&p.environment===e&&p.seed===seed);if(!p)throw Error('Missing pair '+h+e+seed);return p;};
const pairs=[find('cql','hopper'),find('cql','walker2d'),find('td3_bc','walker2d')];

let s=add('Why are we doing this study?',`Advisor question: Why do this, and what does it accomplish? Our objective is to test whether BCA improves decisions involving poorly represented actions. A high whole-policy return does not identify OOD handling, and a small Bellman error does not establish true long-run value accuracy. BCA fits prediction errors against bootstrapped targets, not known true Q-values. We separate warning quality, first-action choice and behavior after the same imposed action. The hypothesis is that learned residual scale can guide useful host-specific caution; this is not an established causal mechanism. Standard BCA keeps Bayesian and conformal components with equal calibration-fitting importance factors.\n${protocol}\n${weighted}`,'Advisor update | September 29, 2026 | Standard BCA first; importance weighting later');
call(s,'Does BCA help when an action has little support in the dataset?',62,145,1140,105,40);
bullets(s,['Why: training reward alone cannot tell us how the agent handles unfamiliar actions.','Test: do BCA warnings identify harmful actions, and does its policy handle them better?','Benefit: locate the limitation before deciding what to change.'],72,290,1120,285,32);
call(s,'Expected result: useful warnings AND better behavior, repeated across seeds.',64,597,1140,43,26);

s=add('What does the experiment actually do?',`Advisor question: What does the experiment accomplish? Policies and the calibrator are frozen during OOD evaluation. Calibration itself uses reserved offline transitions, not these simulator rollouts. We capture full simulator states under both collectors, precommit actions/randomness/widths, then restore each state and impose the same first action under host and BCA continuations. Return is raw and undiscounted over up to 250 total transitions including the first action; natural terminations and original time limits remain. Action-support distance is a proxy: minimum RMS action distance to recorded actions among 32 nearby recorded observations. The predeclared q95/q99 support bands are not proof of exact OOD status, and distant is not synonymous with harmful. First-action quality is also compared with later policy held fixed.\n${protocol}`,'These are simulator tests after training. No policy or calibrator learning occurs during them.');
table(s,[['Step','What we do','Question answered'],['1. Freeze','Use trained host and BCA policies','Which learned policy are we testing?'],['2. Match','Restore the same state and first action','Is the starting situation comparable?'],['3. Stress','Try near, moderate and distant actions','Does action support matter?'],['4. Measure','Let each policy continue; record return','What actually happens afterward?'],['5. Compare','Check behavior, warning scores and seeds','Is any benefit useful and repeatable?']],[175,535,466],{y:153,h:458,size:25});

s=add('Why these experimental choices?',`Advisor question: Justify each change and say why it makes sense. The revised protocol was declared after inspecting the first study, before revised outcomes; it is a prospective follow-up, not original preregistration. Near/moderate/strong action bands improve representation of support levels. Both policies use the same nearest-recorded familiar-action anchor, and we report absolute stressed return as well as relative degradation, so a weak anchor baseline cannot masquerade as robustness. State-near is the primary action-shift population; state-distant is a separate joint-shift sensitivity. Five independent training seeds are the replication unit; correlated rollouts do not create extra training seeds. Coverage stays alpha 0.1; both BCA components and scientific tolerances stay unchanged. The explicitly approved Walker candidate seed correction changed only 404735174 to 404735181 to remove a stream collision, without selecting based on outcomes. Engineering corrections preserve original failures and completed outcomes.\n${protocol}\n${source('docs/OOD_V2_STREAM_AMENDMENT_20260928.md')}`,'The follow-up changes the measurement design; it does not tune coverage or replace unfavorable results.');
table(s,[['Choice / change','Why it is needed','What we expect to learn'],['Standard BCA before IW','Avoid changing two mechanisms at once','Does basic BCA help?'],['Three action-support bands','A few distant examples are insufficient','Does robustness vary with support?'],['Shared familiar-action anchor','Relative losses need a common reference','Less degradation or just a weaker baseline?'],['Separate action and state shift','Unfamiliar states can confound the test','Which type of shift matters?'],['Five training seeds','One favorable run may be accidental','Does the effect repeat?']],[355,405,416],{y:152,h:464,size:24});

s=add('Where are we now?',`These are frozen, sourced counts, not a live claim. Training extraction was September 29 12:59–13:02 UTC; revised OOD snapshot was 12:52 UTC, equivalent to approximately 8:52–9:02 a.m. EDT. There are 94 produced physical training results out of 280: 93 successful processes plus one reviewed recovery retaining original CQL exit 1. Eight host/BCA training pairs have full independent reviews; produced results are not all scientifically accepted. There are 115 actor trajectories because IQL BCA physical runs include paired actors sharing nuisance Q/V; 46 saved within-seed comparisons are available. Training grid: four hosts, seven datasets, five seeds. Revised OOD first tranche: TD3+BC/ReBRAC × Hopper/Walker × five seeds =20 pairs, of which five are active and none complete; fifteen unstarted. One earlier TD3+BC Hopper pilot seed is complete and remains separate. Two A100 training lanes and four cluster CPU OOD workers, plus one local CPU OOD worker, were active in this snapshot. CQL's result-field validator was corrected after training finished, without rerunning it. The local OOD continuation preserves completed outcomes after a database-lock failure; active scientific databases must not be audited while writers are running.\n${current}\n${source('docs/OOD_ACTION_COLLECTION_STATUS.md')}`,'Frozen snapshot: Sep 29, approximately 9:00 a.m. EDT. Counts distinguish results produced from reviewed results.');
table(s,[['Workstream','Progress','What that means'],['Training grid','94 / 280 results produced','Eight training pairs independently reviewed'],['Original OOD pilot','One TD3+BC Hopper seed complete','Initial evidence; not the revised experiment'],['Revised OOD tranche','5 active / 20 pairs; 0 complete','TD3+BC and ReBRAC, Hopper and Walker'],['Resources','2 A100 training lanes + CPU OOD','Cluster and local execution both in use']],[320,415,441],{y:156,h:340,size:25});
call(s,'CQL’s output check is corrected; its finished training was preserved.',63,526,1150,45,27);
call(s,'Current bottleneck: finish simulator collection and verify saved outcomes.',63,589,1150,45,27);

s=add('New training results: mixed, not a clear win',`These three pairs use training seed 202609171, one million host updates, a separate 20-episode final bank, and 200 equally spaced periodic banks from 5k to 1M. Average-curve difference is the arithmetic mean of periodic-bank means, not the final periodic evaluation or selected best checkpoint. TD3+BC Walker is independently reviewed. CQL pairs are preliminary saved-evaluation comparisons pending full independent audits; CQL Hopper's host ran on local RTX5070Ti while its BCA counterpart ran on A100, a further qualification. All values are normalized scores for the named dataset and are not aggregated across datasets. Final endpoint and learning-time behavior answer different questions. TD3 Walker BCA wins only eight of twenty paired final resets despite a higher mean; those episodes are not independent training seeds. None of these training evaluations establish action-stress robustness.\n${current}`,'Seed 202609171 only. TD3+BC reviewed; CQL preliminary. CQL Hopper also differs in training hardware.');
text(s,'Normalized score; change = BCA minus host. Curve = average across periodic evaluations.',63,130,1150,42,23,C.muted);
table(s,[['Pair','Host final','BCA final','Final change','Curve change'],...pairs.map((p,i)=>[['CQL Hopper','CQL Walker','TD3+BC Walker'][i],p.host_final.toFixed(2),p.bca_final.toFixed(2),fmt(p.final_difference),fmt(p.curve_difference)])],[360,185,185,225,221],{y:185,h:285,size:27});
call(s,'TD3+BC Walker ends higher, but its average learning curve is lower.',63,506,1150,60,29);
call(s,'Meaning: a better endpoint is not yet evidence of a better OOD mechanism.',63,590,1150,52,28);

s=add('The learning curves explain that distinction',`Each native editable chart uses every saved periodic-bank mean, no smoothing or selected checkpoints. Host is navy; BCA is teal. All use training seed 202609171. Each periodic bank contains ten episodes in these hosts, with evaluation seeds pinned. Axes show normalized score and thousands of host updates. The final reserved bank in the prior slide is separate, so its mean need not equal the final point plotted here. CQL saved summaries remain preliminary, and CQL Hopper has different training hardware across arms. These plots describe policy performance while learning, not harm ranking or conformal coverage.\n${current}`,'All 200 periodic means; no smoothing. Final reserved-bank scores are separate. CQL remains preliminary.');
for(let i=0;i<pairs.length;i++){const p=pairs[i];const a=data.records.find(r=>r.run_id===p.host_run&&r.arm==='host');const b=data.records.find(r=>r.run_id===p.bca_run&&r.arm==='bca');if(!a||!b)throw Error('record missing');
 text(s,['CQL · Hopper','CQL · Walker','TD3+BC · Walker'][i],55+i*405,140,376,42,28,C.navy,true);
 text(s,'Normalized score',55+i*405,183,376,30,19,C.muted);
 chart(s,'scatter',{position:{left:43+i*405,top:216,width:390,height:343},series:[{name:'Host',xValues:a.steps.map(x=>x/1000),values:a.means.map(x=>Number(x.toFixed(8))),line:{fill:C.navy,width:2},marker:{symbol:'none'}},{name:'BCA',xValues:b.steps.map(x=>x/1000),values:b.means.map(x=>Number(x.toFixed(8))),line:{fill:C.teal,width:2},marker:{symbol:'none'}}],hasLegend:true,legend:{position:'bottom',textStyle:{fontSize:19}},yAxis:{min:0,max:120,majorUnit:40,numberFormatCode:'0',textStyle:{fontSize:18},majorGridlines:{fill:C.line,width:1}},xAxis:{min:0,max:1000,majorUnit:500,numberFormatCode:'0',title:'Updates (thousands)',textStyle:{fontSize:18}},scatterOptions:{style:'line'}});
}
call(s,'BCA does not consistently stay above its host across training.',62,591,1140,52,31);

s=add('First OOD pilot: benefit is not established',`Advisor questions: How did we establish weak evidence, and does it meet expectations? This is the completed original TD3+BC Hopper study, training seed 202609171, not the new revised protocol. There are 5120 rollouts, 1280000 outcome steps, 256 captured state rows and 64 shared reset blocks. Harm is loss >1 raw reward versus the host first action under BCA continuation. There are 276 harmful alternatives among 2304 and 111/256 panels with both classes. The chart is the equal-four-stratum mean of within-state AUROC; constant gives 0.5, fixed random realizes .513251. Pooled width AUROC .431776 answers a different question. These descriptive differences are not significance claims. Expected wider bands to rank harmful actions and BCA behavior to improve; observed ranking is near chance and no average first-action gain. BCA minus host first-action return under the same BCA continuation is -.120. Separate post-hoc distant-action bridge (233 actions in193 states) has absolute continuation return difference -5.046 and relative degradation advantage -.019; it is unbalanced and is not revised OOD evidence. The reason for weak performance is not identified: residual target, scale ranking, host attachment and distribution shift remain competing explanations.\n${pilot}`,'Original pilot only: TD3+BC Hopper, one seed. Revised OOD results remain pending.');
text(s,'Ability to rank harmful actions (AUROC)',58,148,760,43,28,C.navy,true);
chart(s,'bar',{position:{left:49,top:218,width:743,height:355},categories:['BCA width','Distance','Random','Constant'],series:[{name:'Within-state AUROC',values:[.529327,.565805,.513251,.5],fill:C.teal,dataLabelOverrides:[.529327,.565805,.513251,.5].map((v,idx)=>({idx,text:v.toFixed(3),showValue:false,position:'outEnd',textStyle:{fontSize:23,typeface:font}}))}],barOptions:{direction:'column',grouping:'clustered',gapWidth:75},hasLegend:false,dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:23,typeface:font}},yAxis:{min:0,max:1,majorUnit:.25,numberFormatCode:'0.00',textStyle:{fontSize:20},majorGridlines:{fill:C.line,width:1}},xAxis:{textStyle:{fontSize:20}}});
call(s,'0.5 = chance ranking',830,195,385,60,30);
bullets(s,['Width is only slightly above chance.','The expected warning benefit is not convincing yet.','One seed cannot establish a general failure or success.'],830,292,383,285,27);
call(s,'BCA first-action gain: −0.12 raw return under the same later policy.',63,599,1150,43,27);

s=add('Why we need all five training seeds',`All three plotted ReBRAC Walker pairs have independent reviews. Training seeds are 202609171, 202609172,202609173. Values are differences between separate-final-bank means, BCA minus host, in normalized score units. Arithmetic mean difference is11.8775121, but one seed contributes33.6399399 while another is negative. This does not provide a five-seed replicated effect or establish OOD performance. Twenty final episodes per run improve evaluation precision but do not create twenty independently trained models. The example is about training variability and responsible interpretation; it is not evidence of why a host attachment succeeds or fails. ReBRAC Hopper's three reviewed seed differences average approximately-.03, nearly tied.\n${current}`,'ReBRAC Walker · 3 of 5 declared seeds · final normalized-score change, BCA minus host');
const seedPairs=[171,172,173].map(k=>find('rebrac','walker2d',202609000+k));const v=seedPairs.map(p=>Number(p.final_difference.toFixed(8)));
chart(s,'bar',{position:{left:55,top:180,width:745,height:425},categories:['Seed 171','Seed 172','Seed 173'],series:[{name:'BCA minus host',values:v,fill:C.teal,dataLabelOverrides:v.map((x,idx)=>({idx,text:fmt(x),showValue:false,position:'outEnd',textStyle:{fontSize:25,typeface:font}}))}],barOptions:{direction:'column',grouping:'clustered',gapWidth:90},hasLegend:false,dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:25,typeface:font}},yAxis:{min:-10,max:40,majorUnit:10,numberFormatCode:'0',textStyle:{fontSize:22},majorGridlines:{fill:C.line,width:1}},xAxis:{textStyle:{fontSize:23}}});
call(s,'Mean change: +11.88',838,183,378,65,32);
bullets(s,['One large gain drives the mean.','Another seed favors the host.','Finish the declared seed set before claiming reliability.'],838,297,374,265,28);

s=add('What would good or bad OOD results mean?',`Advisor question: What do results mean for BCA? Primary action-stress performance A=G_BCA(s,a)-G_host(s,a) after the same imposed action. Relative degradation D=[G_host(s,a0)-G_host(s,a)]-[G_BCA(s,a0)-G_BCA(s,a)], with shared recorded-action anchor a0. We report both and each anchor return; D alone can be favorable because the baseline is weak. Strong support distance at state-near states is primary. The frozen protocol requires all five seeds and positive multiplicity-adjusted lower bounds for both A and D for a directional robustness claim (eight endpoints; two-sided99.375% intervals); ordinary95% intervals are descriptive. Within-state width ranking is secondary, pooled ranking distinct, and regret among tested actions is exploratory, not regret against the optimal policy. Fresh residual coverage is a separate unavailable measurement: weak harm ranking does not disprove a conformal theorem. Warning-good/behavior-bad is a lead about host use, not identified causality.\n${protocol}\n${weighted}`,'Interpret within each dataset and across training seeds. Coverage, harm ranking and policy return are different claims.');
table(s,[['Observed result','Meaning','Next question'],['Higher stressed return AND less degradation','Evidence of useful action-stress robustness','Does it repeat across all five seeds?'],['Good warnings; weaker behavior','Warning may not be used effectively','Where does the host consume the width?'],['Warnings rank harm poorly','Residual scale may be a weak harm proxy','Is the error target aligned with decision harm?'],['Lower return after the same action','No benefit in that measured setting','Which mechanism explains the loss?']],[400,418,358],{y:155,h:436,size:25});
call(s,'An OOD outcome tells us what to investigate; it does not identify the training cause.',62,607,1153,40,25);

s=add('What is wrong with the current IW approach?',`Advisor questions: Which component was wrong relative to intent, what changes, why? Earlier importance weighting changed the scale-fitting loss, but the radius stage remained effectively an equal-mass held-out conformal calculation with query mass1 and a global radius cache. That is not the intended covariate-shift weighted conformal prediction. The correction uses score S_i=|Y_i-m(X_i)|/sigma(X_i), weights w(X_i)=dQ_X/dP_X, and query weight w(x) at infinity in the weighted1-alpha quantile. Target Y is the frozen one-step bootstrap response, not true Q. Both Bayesian and conformal components remain and their maximum is retained. Finite calibration mass insufficient for the level must yield infinity, not an arbitrary cap. Exact-ratio toy/reference and CPU boundary checks pass, not four-host real-data integration. Real target/source population, support overlap, unchanged Y|X, justified ratios, independently frozen scoring/calibration, query-aware host integration and infinite-radius behavior remain requirements. Estimated ratios are approximate, and deterministic policy targets can be singular. First test radius correction with fitting fixed; fitting IW is a separate comparison. It cannot fix absent support or automatically repair within-state harm ranking.\n${weighted}`,'Standard BCA is the current baseline. Corrected weighted conformal is a separate, not-yet-deployed method.');
table(s,[['Component','Current implementation','Needed for intended method'],['Scale fitting','Some earlier arms reweighted fitting errors','Keep fixed first to isolate the correction'],['Conformal threshold','Held-out scores effectively had equal masses','Use target/source weights and the query’s mass'],['Validation','CPU/reference mathematics checked','Validate real-data assumptions and host integration']],[270,453,453],{y:171,h:305,size:25});
call(s,'Why it could help: calibrate for the population where predictions will be used.',64,512,1148,66,29);
call(s,'Why it may not: weighting cannot create missing evidence or guarantee better actions.',64,592,1148,55,28);

s=add('Next steps: finish, diagnose, then change',`Advisor question: What do we do next, and why? Finish the five active revised OOD pairs and independently validate saved outcomes before presenting readouts. Finish all20 declared first-tranche pairs with five seeds per cell; CQL/IQL and other-dataset OOD adapters remain separate work, so training completion is not OOD completion. Report A,strong and D,strong, familiar baselines, missing support quotas/states, uncertainty and within-state ranking. Preserve all negative findings and original failures. The next method depends on evidence: weak ranking motivates investigating residual target/scale; useful warnings but weaker policies motivates controlled host-attachment tests; justified population shift motivates query-aware weighted conformal. Each intervention needs a declared hypothesis, a matching control and a pass/fail reading. No claim IW must improve results, no coverage or strength tuning yet. A responsible final statement is: current evidence does not demonstrate the desired BCA OOD benefit, and the revised experiment is designed to identify the limitation rather than select favorable cases.\n${protocol}\n${weighted}\n${current}`,'Meeting message: the present evidence is weak; the next experiment must identify the limitation, not assume the fix.');
table(s,[['Next action','Why','Deliverable'],['Finish and verify active OOD pairs','Obtain real, comparable outcomes','Stressed return, degradation and warning plots'],['Complete the five-seed tranche','Separate repeatable effects from randomness','All seed effects and uncertainty'],['Diagnose the observed limitation','Avoid changing the wrong component','Target/scale, host attachment or population shift'],['Test one justified change at a time','Make any improvement interpretable','Standard BCA versus a declared correction']],[398,408,370],{y:173,h:395,size:26});
call(s,'No coverage tuning yet. Importance weighting remains a testable hypothesis.',64,598,1148,48,29);

const candidate=build+'/candidate-v4.pptx';
await (await PresentationFile.exportPptx(pres)).save(candidate);
const publicSlides=slides.map(({slide,...x})=>x);
await fs.writeFile(build+'/slide_content.json',JSON.stringify(publicSlides,null,2));
const md=['# BCA advisor update — September 29, 2026','Data snapshot: approximately 9:00 a.m. EDT. Original pilot evidence is labelled separately.','',...publicSlides.flatMap((x,i)=>['## Slide '+(i+1)+': '+x.title,'',...x.callouts.map(t=>t+'\n'),...x.bullets.map(t=>'- '+t),...(x.table?['',...x.table.map((r,j)=>'| '+r.join(' | ')+' |'+(j===0?'\n| '+r.map(()=>'---').join(' | ')+' |':''))]:[]),'','**Speaker notes**','',x.notes,''])].join('\n');
await fs.writeFile(out+'/SPEAKER_NOTES.md',md);
const final=out+'/BCA_Advisor_Answers_2026-09-29_reviewed.pptx';
await finalizePresentation({workspaceDir:W,candidatePath:candidate,finalPath:final,pythonExecutable:'C:/Users/David Bayha/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...[...new Set(tableSlides)].flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeTableOwnerSlides:[...new Set(tableSlides)],requiredNativeChartOwnerSlides:[...new Set(chartSlides)],materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:build+'/validation-v4.json'});
const imported=await PresentationFile.importPptx(await FileBlob.load(final));
for(let i=0;i<slides.length;i++){const png=await imported.export({slide:imported.slides.items[i],format:'png',scale:1});await fs.writeFile(out+`/slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await png.arrayBuffer()));}
await fs.writeFile(out+'/EVIDENCE.json',JSON.stringify({source:R+'/outputs/current_results/2026-09-29/plot_data.json',source_publication:'55a741720c3a847b05196484fd79a5e55fe50358',training_snapshot:data.training_captured_utc,ood_snapshot:data.ood_captured_utc,pairs,rebrac_walker:seedPairs,pilot_source:R+'/outputs/advisor_progress/2026-09-29/ADVISOR_BRIEF.md',slide_count:slides.length,native_chart_slides:[...new Set(chartSlides)],native_table_slides:[...new Set(tableSlides)]},null,2));
console.log(JSON.stringify({final,slides:slides.length,output:out,font}));
