import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation,PresentationFile,FileBlob} from '@oai/artifact-tool';
const W='C:/Users/David Bayha/Documents/Codex/2026-09-09/this-is-my-phd-research-im';
const R='C:/Users/David Bayha/Documents/GitHub/BCA';
const skill='C:/Users/David Bayha/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
const build=W+'/work/advisor_metrics_20260929/build';
const out=W+'/outputs/advisor_metrics_20260929';
await fs.mkdir(out,{recursive:true});
const {resolvePresentationFont,applyPresentationChartFont,makeNativeBulletParagraphs,finalizePresentation}=await import(pathToFileURL(skill+'/container_tools/artifact_tool_utils.mjs'));
const font=resolvePresentationFont();
const data=JSON.parse(await fs.readFile(R+'/outputs/current_results/2026-09-29/plot_data.json','utf8'));
const C={navy:'#20365C',ink:'#192737',teal:'#087F8C',orange:'#B46226',muted:'#5C6877',pale:'#F1F4F8',line:'#D8DFE7',white:'#FFFFFF'};
const pres=Presentation.create({slideSize:{width:1280,height:720}});
const slides=[], tableSlides=[], chartSlides=[];
const source=p=>'Evidence: '+R+'/'+p;
const current=source('outputs/current_results/2026-09-29/plot_data.json')+'\n'+source('outputs/current_results/2026-09-29/ANALYSIS.md');
const protocol=source('docs/superpowers/plans/2026-09-28-ood-robustness-v2.md');
const pilot=source('outputs/advisor_progress/2026-09-29/ADVISOR_BRIEF.md');
const weighted=source('docs/WEIGHTED_CONFORMAL_DESIGN.md');
function text(sl,t,x,y,w,h,size=28,color=C.ink,bold=false){const sh=sl.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});sh.text=t;sh.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none',verticalAlignment:'middle'};return sh;}
function add(title,notes,footer=''){const sl=pres.slides.add();sl.background.fill=C.white;sl.shapes.add({geometry:'rect',position:{left:0,top:0,width:1280,height:110},fill:C.navy,line:{fill:'none',width:0}});text(sl,title,52,19,1176,75,42,C.white,true);text(sl,footer,54,660,1090,37,17,C.muted);text(sl,String(slides.length+1),1180,660,48,37,18,C.muted);sl.speakerNotes.textFrame.setText(notes);slides.push({title,notes,footer,slide:sl,bullets:[],callouts:[]});return sl;}
function call(sl,t,x,y,w,h,size=30,color=C.navy,bold=true){slides.at(-1).callouts.push(t);return text(sl,t,x,y,w,h,size,color,bold);}
function bullets(sl,items,x=66,y=185,w=1145,h=385,size=30){slides.at(-1).bullets.push(...items);const sh=text(sl,'',x,y,w,h,size);sh.text=makeNativeBulletParagraphs(items,{marginLeftPoints:18,hangingPoints:9,spaceAfterPoints:19});sh.text.style={typeface:font,fontSize:size,color:C.ink,autoFit:'none'};return sh;}
function table(sl,values,widths,{x=52,y=173,h=400,size=25}={}){const t=sl.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width:widths.reduce((a,b)=>a+b,0),height:h,columnWidths:widths,values});t.borders.assign({fill:C.line,width:1,style:'solid'});for(let r=0;r<values.length;r++){t.rows[r].height=h/values.length;for(let c=0;c<values[0].length;c++){const ce=t.getCell(r,c);ce.fill=r===0?C.navy:r%2?C.white:C.pale;ce.text.style={typeface:font,fontSize:size,color:r===0?C.white:C.ink,bold:r===0,autoFit:'none'};}}t.cells.block({row:0,column:0,rowCount:values.length,columnCount:values[0].length}).assign({margins:{left:12,right:10,top:8,bottom:7},anchor:'center'});tableSlides.push(slides.length);slides.at(-1).table=values;return t;}
function chart(sl,type,config){const c=sl.charts.add(type,{chartFill:C.white,plotAreaFill:C.white,chartLine:{fill:'none',width:0},...config});applyPresentationChartFont(c,{fontFamily:font});chartSlides.push(slides.length);return c;}
const fmt=x=>(x>=0?'+':'−')+Math.abs(x).toFixed(2);
const find=(h,e,seed=202609171)=>{const p=data.paired_summaries.find(p=>p.host===h&&p.environment===e&&p.seed===seed);if(!p)throw Error('Missing pair '+h+e+seed);return p;};
const pairs=[find('cql','hopper'),find('cql','walker2d'),find('td3_bc','walker2d')];

const M=JSON.parse(await fs.readFile(path.dirname(build)+'/metrics.json','utf8'));
const P=M.pilot.bca.overall;
const D=(h,arm)=>M.metrics[`${h}-walker2d-${arm==='host'?'host':'bca-noiw'}-s202609171`];
const TD=D('td3_bc','bca'),RB=D('rebrac','bca');
const evidence='Saved closed exports; no live simulator archives or checkpoints queried.\n'+source('outputs/ood/td3_bc/hopper/s202609171/real-harm-report-v1/summary.json')+'\n'+source('outputs/ood/td3_bc/hopper/s202609171/real-harm-report-v1/panels.json');
const metricsEvidence=source('analysis/current_results_20260929/inputs/local_exports.json')+'\n'+source('analysis/current_results_20260929/inputs/cluster_snapshot.json.gz');
function bar(sl,categories,series,x,y,w,h,min=0,max=1,major=.25){chart(sl,'bar',{position:{left:x,top:y,width:w,height:h},categories,series:series.map(z=>({...z,values:z.values.map(v=>Number(v.toFixed(8))),dataLabelOverrides:z.values.map((v,idx)=>({idx,text:v.toFixed(max===1?3:2),showValue:false,position:'outEnd',textStyle:{fontSize:21,typeface:font}}))})),barOptions:{direction:'column',grouping:'clustered',gapWidth:80},hasLegend:series.length>1,legend:{position:'bottom',textStyle:{fontSize:20}},dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:21,typeface:font}},xAxis:{tickLabelPosition:'low',textStyle:{fontSize:20}},yAxis:{min,max,majorUnit:major,numberFormatCode:max===1?'0.00':'0',textStyle:{fontSize:20},majorGridlines:{fill:C.line,width:1}}});}
function line(sl,title,series,x,y,w,h,{min=undefined,max=undefined,unit='Logged value',legend=true}={}){text(sl,title,x+5,y,w-10,37,26,C.navy,true);text(sl,unit,x+5,y+39,w-10,24,18,C.muted);chart(sl,'scatter',{position:{left:x,top:y+66,width:w,height:h-66},series:series.map(z=>({name:z.name,xValues:z.steps.map(t=>t/1000),values:z.values.map(v=>Number(v.toFixed(8))),line:{fill:z.color,width:1.6},marker:{symbol:'none'}})),hasLegend:legend,legend:{position:'bottom',textStyle:{fontSize:20}},scatterOptions:{style:'line'},xAxis:{min:0,max:1000,majorUnit:250,numberFormatCode:'0',title:'Host updates (thousands)',textStyle:{fontSize:18}},yAxis:{...(min!==undefined?{min}:{}),...(max!==undefined?{max}:{}),textStyle:{fontSize:18},majorGridlines:{fill:C.line,width:1}}});}
let s=add('The study needs more than a return curve',`Research objective: Determine whether BCA produces useful prediction-error bands and whether their use by the host improves action decisions. Whole-policy return is only one end result. This deck adds the missing evidence chain: empirical coverage, width/sharpness, warning discrimination, decision regret, scale fitting, component radii, consumed penalty, and critic behavior. Fresh residual coverage is not established. The prior slide deck overemphasized return and omitted already-available calibration diagnostics and secondary pilot metrics. Pilot statistics are one TD3+BC Hopper training seed; training diagnostics below use seed202609171 on Walker. Those are different cells and cannot be merged into a same-run causal explanation. Revised OOD snapshot still has zero completed pairs.\n${evidence}\n${metricsEvidence}`,'Data are saved evidence through Sep 29, approximately 9 a.m. EDT. Pilot and revised OOD remain separate.');
table(s,[['Question','Metric','Evidence available'],['Are bands reliable?','Fresh empirical residual coverage','Not yet verified'],['Are warnings useful?','Within-state AUROC and average precision','Completed Hopper pilot'],['Is unfamiliarity linked to harm?','Support distance versus harm rate','Completed Hopper pilot'],['Are choices better?','Regret among tested actions','Exploratory pilot readout'],['Is BCA working during training?','Scale fits, width, radii and penalty dose','Reviewed TD3/ReBRAC; CQL preliminary'],['What changes in the critic?','Q estimates and Bellman/conservative loss','Training diagnostics; not true-Q error']],[365,414,397],{y:152,h:470,size:24});

s=add('Warnings: some enrichment, weak separation',`Original TD3+BC Hopper pilot, seed202609171, frozen BCA continuation. Harm means losing more than1 raw reward unit relative to host first action in the same state over250 total transitions. Each panel has nine alternatives. AUROC and average precision are computed within eligible panels, then averaged within the four collector/capture strata; the displayed mean gives equal weight to each stratum. There are111/256 eligible panels. All145 single-class panels are N/A for these rankings. AUROC asks how often a harmful action scores above a nonharmful action;0.5 is chance, ties half. AP summarizes precision as high-score actions are selected; higher is better, with tied-score groups handled together. Constant-score AP=.27456 is the matched eligible-panel baseline, not the11.98% pooled harm frequency. AP shows enrichment over constant/random, so it is inaccurate to say the signal contains no information. Width trails support distance on both metrics and AUROC is near chance; no significance or replicated claim. Within-state and pooled statistics remain separate.\n${evidence}`,'Original Hopper pilot, one seed. Equal-stratum within-state summaries; 111/256 eligible panels.');
const names=['Width','Distance','Random','Constant'];
const auc=['width','support','random','constant'].map(k=>P[`balanced_stratum_within_${k}_auc`]);
const ap=['width','support','random','constant'].map(k=>P[`balanced_stratum_within_${k}_ap`]);
text(s,'AUROC: overall harmful/nonharmful separation',53,147,583,70,27,C.navy,true);
text(s,'Average precision: quality of top warnings',679,147,552,70,27,C.navy,true);
bar(s,names,[{name:'AUROC',values:auc,fill:C.teal}],48,229,575,344);
bar(s,names,[{name:'Average precision',values:ap,fill:C.teal}],674,229,557,344);
call(s,'Width carries some signal, but the simple distance warning is stronger here.',63,600,1153,48,28);

s=add('Unfamiliar actions and harmful actions differ',`The same primary BCA-continuation pilot alternatives are used: near2071 with231 harmful, distant233 with45 harmful. Distant/nonharmful188 and near/nonharmful1840. Harm threshold >1 and support threshold .21134613219046514 are unchanged. Support is minimum RMS action distance among32 nearby recorded observations, not exact policy density or true OOD membership. The descriptive rates are231/2071=11.153...% and45/233=19.313...%. Support-distant actions have a higher observed harm rate, yet231/276 harmful alternatives are near and188/233 distant alternatives are not harmful. These correlated actions and shared resets are not independent training seeds. This motivates balanced support bands and direct harm measurements, not labelling every far action dangerous.\n${evidence}`,'Original pilot: 2,304 alternatives, 276 harmful. Harm = loss >1 raw reward versus host first action.');
bar(s,['Support-near','Support-distant'],[{name:'Harm rate (%)',values:[231/2071*100,45/233*100],fill:C.teal}],51,194,660,389,0,25,5);
text(s,'Observed harmful-action rate (%)',59,147,660,40,26,C.navy,true);
bullets(s,['231 of 276 harmful actions were still support-near.','188 of 233 distant actions were not harmful.','Novelty is a useful descriptor, not a harm label.'],761,211,447,354,29);
call(s,'Why test both? BCA must distinguish bad actions, not merely unfamiliar ones.',63,603,1150,44,27);

s=add('Warning quality changes with the situation',`The four primary strata retain both policy collectors at reset and after100 collector steps. Width AUROC and support AUROC differ by stratum. Captured reset states under the collectors can coincide; they are not independent samples. The largest width ranking here is at host-collected step100 states, while the host-reset and BCA-step100 strata are below0.5. Do not select the favorable stratum as the overall result. Across all2560 fixed state-action slots the saved width min/median/max are1.352396965/1.746680200/2.478725672. No panel has all nine alternative widths tied, so the near-chance primary summary is not explained by an all-action constant warning. This does not identify the residual model's causal failure. One positive global radius scales widths without changing within-state ordering.\n${evidence}`,'Original pilot, frozen BCA continuation. All strata are retained; N/A panels are not assigned zero.');
const order=['host/0','host/100','bca/0','bca/100'];
table(s,[['Collected states','Eligible / 64','Width AUROC','Distance AUROC'],...order.map((k,i)=>{const r=M.pilot.bca.strata[k];return [['Host · reset','Host · step 100','BCA · reset','BCA · step 100'][i],String(r.eligible_panels),r.within_width_auc.toFixed(3),r.within_support_auc.toFixed(3)];})],[420,230,263,263],{y:162,h:340,size:27});
call(s,'Widths vary: 1.35–2.48. No panel has all alternative widths tied.',64,527,1150,52,29);
call(s,'Changing one global radius cannot repair which action is ranked as riskier.',64,598,1150,50,28);

s=add('Action choice: regret among tested actions',`Secondary exploratory endpoint declared after collection and before the readout. For a state and fixed continuation c, regret(a)=max over ten tested precommitted unique actions G_c(s,a') minus G_c(s,a). It is not optimal-policy regret, true-Q error or a guarantee about untested actions. All256 captured rows are averaged, including repeated reset blocks. BCA continuation means the same later BCA policy is used to evaluate both candidate first actions. Host continuation likewise holds the later host policy fixed. Mean regret values are6.333291153 and6.452881609 under BCA continuation, and8.242196683 and8.489875844 under host continuation. Their differences equal the negative paired first-action advantage, an arithmetic consistency check. Lower is better, but the small observed differences in one correlated panel are not a significant general disadvantage. This is a local decision metric derived from measured outcomes, separate from whole-policy average return.\n${evidence}`,'Exploratory pilot metric. Best of ten tested actions; 256 captured rows, one training seed.');
bar(s,['BCA later policy','Host later policy'],[{name:'Host first action',values:[P.mean_host_first_tested_bank_regret,M.pilot.host.overall.mean_host_first_tested_bank_regret],fill:C.navy},{name:'BCA first action',values:[P.mean_bca_first_tested_bank_regret,M.pilot.host.overall.mean_bca_first_tested_bank_regret],fill:C.teal}],58,198,1136,373,0,10,2);
text(s,'Mean candidate-set regret (raw reward units; lower is better)',63,145,1130,43,27,C.navy,true);
call(s,'The BCA first action does not reduce average tested-action regret in this pilot.',63,607,1150,44,28);

s=add('Calibration is fitting and changing the penalty',`Standard BCA Walker, seed202609171. Both TD3+BC and ReBRAC audited final checkpoint counters independently record1000000 accepted scale fits and500000 actor updates. Each plot shows1000 block means covering1000 host updates each. Actor BC multipliers use actual actor rows, excluding skipped-update zeros; genuine active zeros remain. Final block TD3 multiplier1.331356037 andReBRAC1.377447963. Scale-loss final block .0109333582/.0100045581. These are different host-specific models; the scale objectives are not a cross-host quality ranking. Width-dependent multipliers modulate actor behavior-cloning strength; ReBRAC's critic BC stays at its host value. Standard equal fitting factors do not create an importance-weight degeneracy diagnosis. A learned positive dose and accepted updates establish execution, not calibrated coverage, OOD detection or benefit.\n${metricsEvidence}`,'Reviewed standard-BCA Walker runs, seed 202609171. Full block means; actor skip rows excluded.');
line(s,'Scale-fitting objective',[{name:'TD3+BC',steps:TD.steps,values:TD.scale_loss,color:C.navy},{name:'ReBRAC',steps:RB.steps,values:RB.scale_loss,color:C.teal}],53,145,573,426,{min:0,unit:'Block mean objective'});
line(s,'Actor behavior-cloning multiplier',[{name:'TD3+BC',steps:TD.steps,values:TD.actor_bc_multiplier_mean,color:C.navy},{name:'ReBRAC',steps:RB.steps,values:RB.actor_bc_multiplier_mean,color:C.teal}],670,145,553,426,{min:1,max:1.5,unit:'Multiplier; 1 = unchanged strength'});
call(s,'Both accepted 1,000,000 scale fits. Final block strength: ×1.331 / ×1.377.',63,600,1150,48,28);

s=add('Bayesian and conformal components are retained',`These are the198 saved refreshes from10k to995k in each reviewed standard-BCA Walker run; no interpolated or fabricated final1M refresh. The effective radius equals max(Bayesian,conformal) at every saved refresh. The conformal floor is nonbinding at198/198 for both runs; its zero contribution to the max in these observations does not authorize removing it. Bayesian mass draws remain active. TD3 final saved refresh Bayes1.499558091,conformal1.372334599, frozen residual unit5.178395748. ReBRAC units were not in this refresh export, so no unit history is invented. Radii are in normalized residual-score units, not directly Q-value width. Width also depends on the state-action scale and stored unit. Radius evolution is not empirical coverage.\n${metricsEvidence}`,'198 refreshes per run. Effective radius is the larger component; this plot is not a coverage test.');
for(const [i,host,z] of [[0,'TD3+BC',TD],[1,'ReBRAC',RB]]){line(s,host+' · Walker',[["bayesian_radius",C.navy,'Bayesian'],['conformal_radius',C.teal,'Conformal']].map(([k,color,name])=>({name,color,steps:z.refresh.map(r=>r.step),values:z.refresh.map(r=>r.radii[k])})),53+617*i,151,570,415,{unit:'Radius in normalized residual units'});}
call(s,'Conformal is below Bayesian at 198/198 refreshes in each run.',63,592,1150,48,29);
text(s,'The floor remains in the algorithm; a larger global radius cannot improve action ordering.',63,635,1150,30,24,C.muted);

for(const [host,label,qkey,qdescription] of [['td3_bc','TD3+BC','q_mean','Q1 at proposed actor actions'],['rebrac','ReBRAC','q_min','Minimum twin Q at recorded actions']]){
 const a=D(host,'host'),b=D(host,'bca');
 s=add(label+': inspect Q and Bellman loss',`${label} Walker, seed202609171, audited1000-update block means. ${qdescription}. TD3 Q is evaluated after critic update before actor update, on active actor rows; ReBRAC Qmin is pre-critic and retained across all host rows. TD3 and ReBRAC Q summaries are not the same estimand and must not be compared as a shared optimism curve. Critic loss is the host's twin-loss training objective, not measured true-Q error or OOD harm. In these last blocks BCA Q is lower but critic loss is higher. That pattern motivates investigation but does not prove corrected overestimation or excessive pessimism. Actor loss and BC accounting are also available in the saved blocks: TD3 bc_loss includes consumed dose, while ReBRAC bc_mse_policy is an unweighted coordinate sum.\n${metricsEvidence}`,'One reviewed Walker training seed. Training losses are fitting diagnostics, not labels for unsafe actions.');
 line(s,qdescription,[{name:'Host',steps:a.steps,values:a[qkey],color:C.navy},{name:'BCA',steps:b.steps,values:b[qkey],color:C.teal}],53,151,573,419,{unit:'Block mean Q estimate'});
 line(s,'Critic fitting loss',[{name:'Host',steps:a.steps,values:a.critic_loss,color:C.navy},{name:'BCA',steps:b.steps,values:b.critic_loss,color:C.teal}],670,151,553,419,{unit:'Block mean host loss'});
 call(s,`Final block Q: ${a[qkey].at(-1).toFixed(2)} → ${b[qkey].at(-1).toFixed(2)}; critic loss: ${a.critic_loss.at(-1).toFixed(2)} → ${b.critic_loss.at(-1).toFixed(2)}.`,63,595,1150,46,28);
 text(s,'Lower Q does not establish more accurate Q. Larger loss does not identify OOD harm.',63,638,1150,29,24,C.muted);
}

s=add('CQL: inspect its critic and consumed penalty',`CQL Walker seed202609171, preliminary frozen cluster export pending full independent audit.1000 retained last-row observations at1000-update intervals; not full scan means or a million per-update rows. Q1 is on recorded actions. Bellman objective and conservative objective are scalar losses, not gradient norms. BCA width at the recorded transition changes the multiplier on the conservative gap, not a separate warning for each sampled negative action. The fourth chart is that logged multiplier; a nonzero or large multiplier is not coverage or detection. Both Hopper and Walker have198 successful refresh records, but numerical historical CQL radii are unavailable in this export. Sparse accepted scale snapshots do not establish every update accepted; checkpoint review is pending. No counters or radius traces are fabricated.\n${metricsEvidence}`,'CQL Walker: preliminary saved diagnostics. Sparse last-row snapshots; full independent review pending.');
const CA=M.metrics['cql-walker2d-host-s202609171'],CB=M.metrics['cql-walker2d-bca-noiw-s202609171'];
for(const [i,k,title,unit] of [[0,'average_qf1','Q1 at recorded actions','Logged Q1'],[1,'qf1_loss','Bellman fitting loss','Logged objective'],[2,'cql_min_qf1_loss','Conservative objective','Logged objective'],[3,'critic_dose_mean','Conservative-gap multiplier','Logged BCA multiplier']]){
 const series=i===3?[{name:'BCA',steps:CB.steps,values:CB[k],color:C.teal}]:[{name:'Host',steps:CA.steps,values:CA[k],color:C.navy},{name:'BCA',steps:CB.steps,values:CB[k],color:C.teal}];
 line(s,title,series,52+(i%2)*618,131+Math.floor(i/2)*248,572,248,{unit,legend:i<2});
}

s=add('Coverage remains an unanswered question',`Do not replace the missing calibration-validity test with fitted scale loss, successful updates, radius plots or behavioral returns. The required observable is indicator{|Y-m(X)| <= width(X)} on a fresh appropriately held-out population after the scoring function is frozen, with an explicitly declared one-step response/target, sampling design and assumptions. The target is the specified bootstrapped Bellman response, not true infinite-horizon Q. Nominal coverage90% is a configured target, not a measured90% outcome or90% imitation of the old policy. Nominal Bayesian credibility is also not population coverage. Report empirical coverage, interval width/sharpness, sampling uncertainty and predeclared support-stratum diagnostics separately. Conditional group checks are empirical; the marginal theorem is not automatically conditional coverage. Current behavioral archives do not establish fresh residual coverage, and ReBRAC's next-action target contract remains a separate compatibility constraint. Exact weighted-conformal correction needs justified density ratios/support and query mass; fitting weights alone are not sufficient.\n${weighted}\n${protocol}\n${evidence}`,'Important gap: no verified fresh OOD residual-coverage result. Nominal 90% is a target, not a finding.');
table(s,[['Measure','What it answers','Current evidence'],['Empirical residual coverage','How often does the band contain its stated target?','Not verified on fresh OOD samples'],['Band width / sharpness','How much uncertainty does it report?','Pilot widths 1.35–2.48; not coverage'],['Coverage by support band','Where does calibration fail under shift?','Requires a separate accepted readout'],['Fit counts and radius refreshes','Did the calibration machinery operate?','Verified for reviewed TD3/ReBRAC runs'],['True-Q prediction error','Does Q match actual long-run value?','Not supplied by training Bellman loss']],[340,461,375],{y:155,h:459,size:24});

s=add('What the combined metrics mean for BCA',`Advisor questions: Why do the experiment, what does it accomplish, do findings match expectations, and what next? We expected useful calibrated warnings and better decisions. Current evidence establishes active calibration machinery in the reviewed training examples and some average-precision enrichment in the pilot; it does not establish reliable harm separation, reduced action regret, empirical coverage or replicated OOD robustness. The raw weak performance cannot identify one causal fault. Finish the five active revised pairs and all declared seeds, report AUROC/AP and complete-tie risk retention, support-stratified harm and decision regret separately from primary stressed-return/degradation endpoints. Regret remains exploratory and no score threshold is selected from these outcomes. Add a separate accepted fresh residual-coverage test with its own target/independence contract. Diagnose the failure before the next treatment: poor harm ranking concerns residual target/scale; good warnings but weak choices concerns host use; population coverage shift with defensible support/ratios motivates corrected weighted conformal. Preserve all original attempts, alpha and both components; no tuning or training launched for this slide update.\n${protocol}\n${weighted}\n${evidence}`,'One-seed pilot and reviewed training examples. These are leads to test, not identified causes.');
table(s,[['Evidence','What it establishes','Next step and why'],['Fits accepted; multiplier changes','BCA is active during training','Evaluate whether that signal is useful'],['AP enrichment; near-chance AUROC','Some warning information, limited separation','Finish support-balanced, five-seed tests'],['No lower tested-action regret','No demonstrated choice benefit in the pilot','Check warning-to-host influence separately'],['Fresh coverage absent','Calibration validity under shift is unresolved','Measure coverage against a declared target'],['IW only changed fitting previously','Intended weighted-conformal stage was missing','Validate weighted quantile and query mass']],[379,379,418],{y:153,h:465,size:24});

const candidate=build+'/candidate-v1.pptx';
await (await PresentationFile.exportPptx(pres)).save(candidate);
const content=slides.map(({slide,...r})=>r);
await fs.writeFile(build+'/content.json',JSON.stringify(content,null,2));
await fs.writeFile(out+'/SPEAKER_NOTES.md',['# BCA advisor update: metrics beyond return','',...content.flatMap((r,i)=>['## '+(i+1)+'. '+r.title,'',...r.callouts,...r.bullets.map(x=>'- '+x),'',...(r.table?r.table.map((v,j)=>'| '+v.join(' | ')+' |'+(j===0?'\n| '+v.map(()=>'---').join(' | ')+' |':'')):[]),'',r.notes,''])].join('\n'));
await fs.copyFile(path.dirname(build)+'/metrics.json',out+'/METRIC_EVIDENCE.json');
const final=out+'/BCA_Advisor_Metrics_Beyond_Return_2026-09-29.pptx';
await finalizePresentation({workspaceDir:W,candidatePath:candidate,finalPath:final,pythonExecutable:'C:/Users/David Bayha/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...[...new Set(tableSlides)].flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeTableOwnerSlides:[...new Set(tableSlides)],requiredNativeChartOwnerSlides:[...new Set(chartSlides)],materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:build+'/validation-v1.json'});
const rendered=await PresentationFile.importPptx(await FileBlob.load(final));
for(let i=0;i<slides.length;i++){const png=await rendered.export({slide:rendered.slides.items[i],format:'png',scale:1});await fs.writeFile(out+`/slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await png.arrayBuffer()));}
console.log(JSON.stringify({final,slides:slides.length,nativeCharts:chartSlides.length}));
